
// Postgress sql configuration 
spring.datasource.url=jdbc:postgresql://dpg-d6cjrf94tr6s73c7q510-a.singapore-postgres.render.com/moneymanager_vd9n
spring.datasource.username=moneymanager_vd9n_user
spring.datasource.password=xiUiF5EETjGVMWYFG3rH2fTjqPE7CX9F
